# Variables
CXX = g++
CXXFLAGS = -std=c++11 -Wall -pedantic -Wno-dtor-name

all: test_stack1.x in2post.x

test_stack1.x: test_stack1.cpp
	$(CXX) $(CXXFLAGS) test_stack1.cpp -o test_stack1.x

in2post.x: in2post.cpp
	$(CXX) $(CXXFLAGS) in2post.cpp -o in2post.x