# Variables
CXX = g++
CXXFLAGS = -std=c++11 -Wall -pedantic -Wno-dtor-name

all: proj4_driver.x

proj4_driver.x: proj4_driver.cpp bet.cpp
	$(CXX) $(CXXFLAGS) proj4_driver.cpp bet.cpp -o proj4_driver.x